# Generated by Django 3.2.7 on 2021-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
