# Generated by Django 3.2.7 on 2021-11-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contacts_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='user',
        ),
    ]
