# Generated by Django 3.2.7 on 2021-11-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_rooms_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/rooms'),
        ),
    ]
